apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: monitoring
  labels:
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
      version: v1
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
        version: v1
    spec:
      priorityClassName: "system-node-critical"
      imagePullSecrets:
        - name: etocoreinfra-secret
      serviceAccountName: fluentd
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: fluentd
          #image: etocoreinfraregistry.azurecr.io/fluentd-kubernetes-daemonset:v1.13.3-debian-elasticsearch7-1.1
          image: vscojfrogrhel.vsazure.com/infra-images/etocoreinfraregistry.azurecr.io/fluentd-kubernetes-daemonset:v1.13.3-debian-elasticsearch7-1.1
          env:
            - name: FLUENT_ELASTICSEARCH_HOST
              value: "etocentralelastic.vsazure.com"
            - name: FLUENT_ELASTICSEARCH_PORT
              value: "9200"
            - name: FLUENT_ELASTICSEARCH_SCHEME
              value: "https"
            # Option to configure elasticsearch plugin with self signed certs
            # ================================================================
            - name: FLUENT_ELASTICSEARCH_SSL_VERIFY
              value: "false"
            # Option to configure elasticsearch plugin with tls
            # ================================================================
            - name: FLUENT_ELASTICSEARCH_SSL_VERSION
              value: "TLSv1_3"
            # X-Pack Authentication
            # =====================
            - name: FLUENT_ELASTICSEARCH_USER
              value: "elastic"
            - name: FLUENT_ELASTICSEARCH_PASSWORD
              value: "y9zlxir1Ji"
  #          - name: FLUENT_ELASTICSEARCH_PASSWORD
   #           value: "changeme"
   #         {{end}}
            - name: SSL_CERT_FILE
              value: "/mt/elk/certs"
            - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
              value: /^(?<time>.+) (?<stream>stdout|stderr)( (?<logtag>.))? (?<log>.*)$/
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          resources:
            limits:
              memory: "4Gi"
              cpu: "2"
            requests:
              cpu: "2"
              memory: "2Gi"
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            # When actual pod logs in /var/lib/docker/containers, the following lines should be used.
            # - name: dockercontainerlogdirectory
            #   mountPath: /var/lib/docker/containers
            #   readOnly: true
            # When actual pod logs in /var/log/pods, the following lines should be used.
            - name: dockercontainerlogdirectory
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluentd-config
              mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: varlog
          hostPath:
            path: /var/log
        # When actual pod logs in /var/lib/docker/containers, the following lines should be used.
        # - name: dockercontainerlogdirectory
        #   hostPath:
        #     path: /var/lib/docker/containers
        # When actual pod logs in /var/log/pods, the following lines should be used.
        - name: dockercontainerlogdirectory
          hostPath:
            path: /var/lib/docker/containers
